### ISSUE TITLE
Install DNSSEC Issue

### ISSUE THREAD

**Issue by marleyjaffe** [Bibi40k/OpenVPN-on-FreeNAS-in-iocage#2]
I am currently getting the below errors when attempting to install. The only steps taken to this point is modifying the settings and running the install step.

```
root@freenas[~/OpenVPN-on-FreeNAS-in-iocage]# cat /root/OpenVPN-on-FreeNAS-in-iocage/openvpn-configs/ovpn-install.log
pkg.freebsd.org's SRV record could not be verified.

pkg.freebsd.org could not be reached via DNSSEC.

pkg.freebsd.org could not be reached via DNS, check OpenVPN's network configuration
```

I am able to ping `pkg.freebsd.org` just fine.

**Comment by Bibi40k** [comment]
first of all, what version do you have ?
rerun the script and print output here.
what other settings did you use ?

**Comment by ColinNg** [comment]
Hi, I'm having the same problem. I'm using 
FreeNAS version: `FreeNAS-11.3-U3.2` (from the Web UI > Gear > About)
`11.3-RELEASE-p10` (from the Web UI > Jails > Release)
and from the script:
```
FreeNAS version: [ 11.3-RELEASE-p9 ]
Iocage version: [ 11.3-RELEASE ]
```

After the script fails (same output as marleyjaffe), I did this:
```
root@server[~/OpenVPN-on-FreeNAS-in-iocage]# jexec 5 sh
# host pkg.freebsd.org
;; connection timed out; no servers could be reached
```

If I go to the Web UI > Jails, Stop the jail, Edit the jail disable the checkboxes: `VNET` and `Berkeley Packet Filter` then jexec back in, I can then get an answer for `host pkg.freebsd.org`. 

```
root@server[~/OpenVPN-on-FreeNAS-in-iocage]# jexec 7 sh
# host pkg.freebsd.org
pkg.freebsd.org is an alias for pkgmir.geo.freebsd.org.
pkgmir.geo.freebsd.org has address 204.15.11.114
pkgmir.geo.freebsd.org has IPv6 address 2620:11c:5001:1118:1337::3
```

**Comment by Bibi40k** [comment]
you can also use `iocage console <jail_name>` instead of jexec
glad you solve it
